### ISSUE TITLE
menu list items not visible. the "more" button is also not visible.

### ISSUE THREAD

**Issue by amkumaran** [352Media/flexMenu#24]
I am using flexmenu as described here.

files used:
>flexmenu.css
>modernizr.custom.css
>demo.css
 ><link href='https://fonts.googleapis.com/css?family=Quantico:700' rel='stylesheet' type='text/css'>

I am facing 2 issues.

1. menu list items not visible.   
2. More Button link is not visible.
![issue](https://cloud.githubusercontent.com/assets/16918032/15675641/7d42e07c-2760-11e6-8721-b8d82421530f.png)

**Comment by rdebeasi** [comment]
Hi there! Could you please include a link to the code that's producing this problem? A CodePen or JSFiddle link would be great. Thanks!

**Comment by amkumaran** [comment]
Thanks, the  Dot net Zip file is attached for your info
[flexMenuDotnet.zip](https://github.com/352Media/flexMenu/files/293736/flexMenuDotnet.zip)

**Comment by rdebeasi** [comment]
Thanks for sending that along! Unfortunately, I don't have an ASP.NET development server on which I can test this code. Could you send along a test case that's only HTML, CSS, and JS? You could probably do this by hitting File-->Save As... in your web browser and attaching the results to this ticket.

**Comment by amkumaran** [comment]
here is the html file 
[Accounts1.zip](https://github.com/352Media/flexMenu/files/295363/Accounts1.zip)

**Comment by rdebeasi** [comment]
It looks there are a couple of issues causing this problem. First, flexmenu.js has been included twice. One of those times, it was included above jQuery. This caused a JavaScript error, which stopped the rest of the JavaScript from running.

Second, flexMenu was called above the menu and outside of document ready. This means that it ran before the menu had rendered, and so it was unable to find the menu.

Try removing that first reference to flexmenu.js. Then, try calling flexMenu like this:

```
$( document ).ready(function() {
    $('ul.menu').flexMenu();
});
```

Because this code is wrapped in a call to document ready, it will work even if it's placed before your menu. (You'll still need to put this code after flexMenu and jQuery, of course.) The [jQuery docs](https://learn.jquery.com/using-jquery-core/document-ready/) explain document ready in greater detail if you're interested.

I'll update the readme to clarify when and how to call flexMenu.

Does that help?

**Comment by amkumaran** [comment]
### Excellent !!! that definitely helped.
the flexmenu file appearing twice is typo error.
the Second Solution resolved the issue.
However, i feel the Demo.css has issues. its not handling the sub Menus and More links.
i am used my own css to make it work.
The More alos not handling the Sub menus correctly.
i have to find ways to fix that. anyways. thanks for the help

**Comment by rdebeasi** [comment]
Cool, glad that resolved the issue!
