### ISSUE TITLE
Issue with advance options

### ISSUE THREAD

**Issue by xApep** [352Media/flexMenu#29]
Hi.
no matter what I do, I set threshold, cutoff, linkTextAll or linkTitleAll there is no effect. Just More is always shown.

Any idea?
Kind regards.

**Comment by rdebeasi** [comment]
Hi! Could you please provide an example of the problem you're encountering? A link, CodePen, Gist, or the like would be great. Thanks!

**Comment by EDsolution** [comment]
Hello. Can I send you the link of dev project on your e-mail? It's not for public jet :)

Thanks.

**Comment by rdebeasi** [comment]
Sure! You can reach me at hi@ryandebeasi.com.

**Comment by rdebeasi** [comment]
Hm, it seems to be working properly for me on Firefox and Chrome. On your dev site, I see some menu items followed by a "more" link. If I maximize the window so that there is room for all the nav items, the "More" link disappears and all the nav items are shown.

My screen is 1920px wide with my browser at 1.25 scale, so it's equivalent to 1536px wide.

Am I misunderstanding the problem here?

**Comment by EDsolution** [comment]
Yes, in this point everything is correct, but if you resize to 400px the More is visible but not linkTitleAll. In the 400 px there is no item left only More.

![flexmenu](https://cloud.githubusercontent.com/assets/1315340/17996442/34e8d640-6b69-11e6-9550-197ad78f7fc8.jpg)

**Comment by rdebeasi** [comment]
Archiving this repo and closing all open issues. Thank you so much for your feedback - see you around the internet!! :slightly_smiling_face:
