### ISSUE TITLE
Incompatible Issue

### ISSUE THREAD

**Issue by khleealton** [352Media/flexMenu#30]
Hi,

I would like to ask something about incompatible problems while I run the command "bower install"
The following message is shown:
**flexmenu#1.2 incompatible with 1.4 (latest is 1.1.1)**
I have checked the dependencies and seems my project contains all flexmenu needs. Would you please advise what's the root cause?

Best Regards,
Alton

**Comment by rdebeasi** [comment]
I can reproduce the issue. Looks like Bower doesn't like that I dropped the `v` from the tag a few versions ago and so is stuck on an old version. I'll look into renaming the tag.

In the meantime, you can download flexMenu directly from GitHub to get the latest version, or you can specify 1.1.1 in your bower file until the problem is resolved.

Thanks for the heads-up, and sorry for the hassle!

**Comment by rdebeasi** [comment]
You should now be able to get the new 1.4.1 version through Bower. (Note that the package name has changed from `flexMenu` to `flexmenu` for consistency with Bower's standards.

Again, thanks for filing this issue! :)

**Comment by khleealton** [comment]
Hi! It's working good now. Thanks for your fix!

**Comment by rdebeasi** [comment]
Awesome, glad to hear it! You are very welcome!
