### ISSUE TITLE
Way to Modify the Viewport Width Threshold

### ISSUE THREAD

**Issue by cjkoepke** [352Media/flexMenu#32]
I suppose this is more of a suggestion, but if there's an easy solution I'd gladly implement it locally.

Basically, I need a way to trigger the flex menu relevant to the available **space** in the nav, not the available viewport space.

Specifically, I have a secondary nav floated to the right. The nav I'm initiating the `flexMenu()` function on does not recognize the that secondary nav, and so does not collapse the menu items until after that secondary nav has already broken below the primary.

If you need more explanation, just let me know — any advice would be greatly appreciated. It would also be a very handy option to add for other users I imagine.

**Comment by rdebeasi** [comment]
Would you mind sharing a code example? flexMenu does base its calculations on the space in the nav (not the viewport), so it sounds like you may be encountering a bug.

Thanks!

**Comment by cjkoepke** [comment]
Basic example of how it's setup:

```html
<div class="container-div">
<ul class="primary-nav">
<li>Menu Item</li>
<li>Menu Item</li>
</ul>
<ul class="secondary-nav">
<li>Menu Item</li>
<li>Menu Item</li>
</ul>
</div>
```

```css
.secondary-nav {
float: right;
}
```

```js
( function($) {

	$( document ).ready( function() {
		$( ".primary-nav" ).flexMenu();
	});

})(jQuery);
```

And here's a screenshot of what happens:
<img width="287" alt="screen shot 2016-11-18 at 12 23 17 pm" src="https://cloud.githubusercontent.com/assets/2815568/20443402/e3a7c094-ad89-11e6-996a-bae0d032298b.png">

As you can see, the secondary nav (on the right) is breaking down because the primary nav doesn't start collapsing until the viewport hit's it.

**Comment by rdebeasi** [comment]
Thanks! I think I see what you're saying. It seems like the two menus "compete" for space, and you'd need one to take precedence over the other.

I'd recommend using CSS to allocate the space between the two menus. Flexbox is super-helpful for this: you could say something like, "Give my main menu up to 500px, and give the secondary menu whatever is left." Depending on your use case, simple percentage widths might also be helpful.

I don't plan to add this feature to the library itself because the feature could add a lot of complexity, and because I think this is something that CSS generally handles better than JavaScript.

Hope that helps! 😄

**Comment by cjkoepke** [comment]
@rdebeasi Ah, I didn't realize the CSS effected the plugin function, but that works. Thanks and sorry for the unnecessary issue!

**Comment by rdebeasi** [comment]
No worries at all. It's always interesting to see real-world use cases!
